# Generated by Django 4.2.17 on 2024-12-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='grpc_app_user',
        ),
    ]
