# Generated by Django 4.2.17 on 2024-12-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_app', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
