# Generated by Django 4.2.17 on 2024-12-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_app', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
