# Generated by Django 4.2.17 on 2024-12-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
